name: Merge to gh-pages

on:
  push:
    branches:
      - main

jobs:
  merge-gh-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Merge changes to gh-pages
      run: |
        git remote update
        git fetch
        git checkout gh-pages
        git merge main --no-edit
        git push origin gh-pages
